CREATE TABLE IF NOT EXISTS "user_recreational_locations" (
  id BIGINT PRIMARY KEY,
  title VARCHAR NOT NULL,
  category VARCHAR NOT NULL DEFAULT 'Other',
  address VARCHAR NOT NULL DEFAULT 'N/A',
  link VARCHAR NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  thumbnail VARCHAR,
  images JSON,
  openHours JSON,
  popularTimes JSON,
  description TEXT,
  phone VARCHAR,
  website VARCHAR,
  emails JSON NOT NULL DEFAULT '[]',
  rating NUMERIC,
  reviewRating NUMERIC,
  reviewCount INTEGER,
  reviewsBreakdown JSON,
  reviewsPerRating JSON,
  priceRange VARCHAR,
  timezone VARCHAR,
  plusCode VARCHAR,
  dataId VARCHAR,
  reviewsLink VARCHAR,
  reservations JSON,
  orderOnline JSON,
  menu JSON,
  owner JSON,
  about JSON,
  userReviews JSON,
  userReviewsExtended JSON,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isActive BOOLEAN NOT NULL DEFAULT TRUE
);
